# Generated by Django 4.1.7 on 2023-04-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucoseentry',
            name='customer',
        ),
    ]
