# Generated by Django 4.2 on 2023-04-17 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0003_alter_glucoseentry_measure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoseentry',
            name='guid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
